# Site settings
title: Η Φυσική στο προσκήνιο
email: sch@sch.gr
description: > # this means to ignore newlines until "baseurl:"
  Ασκήσεις Φυσικής όπως παρουσιάζονται στο σχολείο. Μπορείτε να κάνετε αναζήτηση
  χρησιμοποιώντας tag. Ενδεικτικά περιεχόμενα: Μηχανική στερεού, Κινήσεις,
  Δυναμική, Κρούσεις και Ταλαντώσεις
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Petridis_P
github_username:  panagiotis2011

# Build settings
markdown: kramdown
